# Generated by Django 4.1.7 on 2023-03-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelmenu',
            name='HotelName',
            field=models.CharField(choices=[('Andhra Ruchulu', 'Andhra Ruchulu'), ('Love sugar', 'Love sugar'), ('Amritam', 'Amritam'), ('Cheta shop', 'Cheta shop')], default='Andhra Ruchulu', max_length=100),
        ),
        migrations.AlterField(
            model_name='hotelmenu',
            name='category',
            field=models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian')], default='Vegetarian', max_length=100),
        ),
    ]
