# Generated by Django 4.1.7 on 2023-03-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodDB', '0002_hotelmenu_hotelname_alter_hotelmenu_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelmenu',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
